# Generated by Django 3.1.7 on 2021-03-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('num_rooms', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
