# Generated by Django 3.1.7 on 2021-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guest_id', models.IntegerField()),
                ('payment_type', models.CharField(max_length=10)),
                ('credit_card_number', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
