# Generated by Django 3.2 on 2021-04-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('num_rooms', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guest_id', models.IntegerField()),
                ('payment_type', models.CharField(max_length=10)),
                ('credit_card_number', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='ReservationRoomRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
            options={
                'db_table': 'reservation_room_rel',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.IntegerField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
