# Generated by Django 3.2 on 2021-04-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_reservationroomrel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationroomrel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservationroomrel',
            constraint=models.UniqueConstraint(fields=('reservation_id', 'room_id'), name='unique_res_room_relation'),
        ),
    ]
