# Generated by Django 3.2 on 2021-04-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_auto_20210428_0420'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservationroomrel',
            name='unique_res_room_relation',
        ),
        migrations.AlterUniqueTogether(
            name='reservationroomrel',
            unique_together={('reservation_id', 'room_id')},
        ),
    ]
