# Generated by Django 3.2 on 2021-04-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20210428_0422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationroomrel',
            unique_together=set(),
        ),
    ]
