# Generated by Django 3.2 on 2021-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_alter_reservationroomrel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationroomrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservationroomrel',
            name='reservation_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
