# Generated by Django 3.2 on 2021-04-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20210428_0429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationRoomRel',
        ),
    ]
