# Generated by Django 3.2 on 2021-04-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_reservationroomrel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='FeatureRoomRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.feature')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.room')),
            ],
            options={
                'db_table': 'feature_room_rel',
                'unique_together': {('feature_id', 'room_id')},
            },
        ),
    ]
