# Generated by Django 3.2 on 2021-04-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0011_auto_20210429_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoomRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.room')),
            ],
            options={
                'db_table': 'reservation_room_rel',
                'unique_together': {('reservation_id', 'room_id')},
            },
        ),
        migrations.CreateModel(
            name='FeatureRoomRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.feature')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.room')),
            ],
            options={
                'db_table': 'feature_room_rel',
                'unique_together': {('feature_id', 'room_id')},
            },
        ),
    ]
