# Generated by Django 3.2 on 2021-05-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_featureroomrel_reservationroomrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='featureroomrel',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='guest.feature'),
        ),
        migrations.AlterField(
            model_name='featureroomrel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_rooms', to='guest.room'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservationroomrel',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guest.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationroomrel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='guest.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
