# Generated by Django 3.2 on 2021-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0013_auto_20210502_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='credit_card_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
