# Generated by Django 3.2 on 2021-05-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0016_alter_employee_hotel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterUniqueTogether(
            name='featureroomrel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='featureroomrel',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='featureroomrel',
            name='room',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AlterUniqueTogether(
            name='reservationroomrel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservationroomrel',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationroomrel',
            name='room',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='FeatureRoomRel',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationRoomRel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
