# Generated by Django 3.2 on 2021-05-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0017_auto_20210505_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('hotel_id', models.IntegerField(null=True)),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('num_rooms', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guest_id', models.IntegerField()),
                ('payment_type', models.CharField(max_length=10)),
                ('credit_card_number', models.CharField(max_length=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.IntegerField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='ReservationRoomRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guest.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='guest.room')),
            ],
            options={
                'db_table': 'reservation_room_rel',
                'unique_together': {('reservation_id', 'room_id')},
            },
        ),
        migrations.CreateModel(
            name='FeatureRoomRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='guest.feature')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_rooms', to='guest.room')),
            ],
            options={
                'db_table': 'feature_room_rel',
                'unique_together': {('feature_id', 'room_id')},
            },
        ),
    ]
