# Generated by Django 3.1.7 on 2021-05-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0018_employee_feature_featureroomrel_guest_hotel_reservation_reservationroomrel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureroomrel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservationroomrel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
